version: '3'

# Global variables
vars:
  BINARY_DIR: bin
  GAME_BINARY: "{{.BINARY_DIR}}/game"
  GO_FLAGS: '-ldflags="-s -w"'
  WEB_DIR: game_web
  GOROOT:
    sh: go env GOROOT

tasks:
  default:
    desc: Build game
    cmds:
      - task: build
  
  build:
    desc: Build game executable
    cmds:
      - mkdir -p {{.BINARY_DIR}}
      - echo "Building game..."
      - go build {{.GO_FLAGS}} -o {{.GAME_BINARY}} cmd/main.go
      - echo "Build complete!"
    generate:
      - {{.GAME_BINARY}}

  run:
    desc: Run game
    cmds:
      # - task: build
      - echo "Running game..."
      - go run cmd/main.go

  run-web:
    desc: Run game for web (itch.io)
    cmds:
      - task: build-web
      - echo "Running game for web..."
      - go run cmd/testserver/main.go

  build-web:
    desc: Build game for web (itch.io)
    cmds:
      - echo "Copying assets..."
      - cp -r assets {{.WEB_DIR}}
      - mkdir -p {{.WEB_DIR}}
      - echo "Building game for web..."
      - GOOS=js GOARCH=wasm go build {{.GO_FLAGS}} -o {{.WEB_DIR}}/game.wasm cmd/main.go
